version: '3.3'

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file: .env
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
